### ISSUE TITLE
마커 클러스터링 관련 질문 

### ISSUE THREAD

**Issue by easyhooon** [fornewid/naver-map-compose#101]
demo app과 네이버 공식문서를 통해 naver-map 에서 이제 자체적으로 클러스터링을 지원하는 것을 확인했습니다.

혹시 naver-map-compose 에서는 몇버전에서부터 해당 기능을 이용할 수 있는지 알 수 있을까요?
기존 naver-map-compose 1.5.5 버전, location 21.0.1 버전에선 clustering 관련 import 가 이뤄지지 않는 것 같아. 버전을 올려보았는데, 정상적으로 import 가 되지 않는것 같아서 이슈 남깁니다.

**Comment by fornewid** [comment]
지금까지는 배포된 것이 없었구요.
방금 배포한 naver-map-compose [v1.5.7](https://github.com/fornewid/naver-map-compose/releases/tag/v1.5.7)에서 확인 부탁드립니다.

그리고 클러스터링은 나온지 얼마되지 않아서,
Compose에서 사용하기 적합한 형태로 작업이 되지 않았습니다.
참고 부탁드려요.

**Comment by fornewid** [comment]
naver-map-compose 1.5.7, 1.7.0 부터는 저장소 주소를 변경해야 합니다.
(아직 README.md는 수정되지 않았습니다.)

```
https://repository.map.naver.com/archive/maven
```

참고 부탁드려요.

**Comment by easyhooon** [comment]
아하 역시 import 안되던게 제 문제가 아니었군요 이슈 남기기 잘했네요 항상 답변 감사드립니다..!
