### ISSUE TITLE
naver-map-compose 1.7.2 사용 시 compile error가 발생합니다. 

### ISSUE THREAD

**Issue by boming** [fornewid/naver-map-compose#110]
안녕하세요! 라이브러리를 잘 사용하고 있습니다. 

최근에 naver-map-compose 를 1.5.7 -> 1.7.2 로 변경하려고 했는데 아래와 같은 에러가 발생합니다. 
compose-bom 2024.06.00 을 사용하고 있고, 혹시나 2024.05.00 에서는 문제가 발생하지 않는지 확인해봤는데 동일하게 빌드 에러가 발생합니다. 
한번 확인 부탁드립니다.

감사합니다.

```
> Task :feature-home:kaptGenerateStubsDebugKotlin
[Fatal Error] map-sdk-3.18.0.pom:2:10: doctype이 이미 표시되었습니다.
[Fatal Error] map-sdk-3.18.0.pom:2:10: doctype이 이미 표시되었습니다.

> Task :feature-home:kaptGenerateStubsDebugKotlin FAILED
e: Could not load module <Error module>
```

**Comment by fornewid** [comment]
1.7.2 버전은 Compose 1.7 버전과 호환되는 버전입니다.
compose-bom 버전을 봐서는 Compose 1.6을 사용하시는 것으로 보이는데요.
버전 차이로 보입니다.

**Comment by fornewid** [comment]
Compose 1.7로 업데이트 할 때에도 naver-map-compose 1.7.X 버전 사용시 이슈가 있다면 말씀해주세요. ㅎㅎ

**Comment by boming** [comment]
> Compose 1.7로 업데이트 할 때에도 naver-map-compose 1.7.X 버전 사용시 이슈가 있다면 말씀해주세요. ㅎㅎ

오 죄송합니다. 2024.06.00 bom이 1.7 대를 사용하고 있는 걸로 착각 했습니다. 🙏  답변 감사합니다
