### ISSUE TITLE
R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable

### ISSUE THREAD

**Issue by park-kyunghyun** [fornewid/naver-map-compose#112]
빌드 시, 

WARNING: /Users/xxx/.gradle/caches/transforms-3/38e599631f0590dd9a5622cf263ba565/transformed/map-sdk-3.18.0-runtime.jar: R8: Expected stack map table for method with non-linear control flow. In later version of R8, the method may be assumed not reachable.

와 같이 워닝이 발생하고 있습니다.
실제 사용에는 큰 문제는 발생하지 않지만 원인을 알 수 있을까요?

**Comment by fornewid** [comment]
`map-sdk-3.18.0-runtime.jar`는 naver-map-compose가 아닌, 네이버지도 SDK 라서요.
네이버지도 SDK에 문의해보시는 것이 좋을 것 같습니다.

**Comment by park-kyunghyun** [comment]
답변 감사드립니다.
