### ISSUE TITLE
Failed to resolve: io.github.fornewid:naver-map-compose:1.2.3

### ISSUE THREAD

**Issue by fivelayer** [fornewid/naver-map-compose#51]
repositories {
    mavenCentral()
}
설정을 했음에도 의존성을 다운하지 못하는 것 같은데요, 버전을 바꿔도 동일합니다.
혹시 지금 다운로드가 안되는 상태인가요?

추가로 https://androidexample365.com/naver-map-android-sdk-for-jetpack-compose/ 이 문서에는
```
// NAVER Map Android SDK 최신 버전도 포함해야 합니다.
    implementation 'com.naver.maps:map-sdk:3.15.0'
```
이런 설명도 있던데, github README 에는 보이질 않아서요. naver map sdk도 추가를 해야하는걸까요?

**Comment by fornewid** [comment]
NAVER Map Android SDK 의존성을 추가하는 것과
다운로드가 안되는 것은 관계가 없는 부분입니다. :eyes:

슬랙으로 답변드린 것처럼 저는 다운로드가 잘되고 있어서
로컬 개발환경의 문제인 것 같습니다. ㅎㅎ

**Comment by fornewid** [comment]
슬랙에서 오간 내용을
`README.md`에 주의사항으로 추가해뒀습니다.

https://github.com/fornewid/naver-map-compose/blob/main/README.md#warning-%EC%A3%BC%EC%9D%98%EC%82%AC%ED%95%AD

해결된 것으로 보여 이슈는 닫겠습니다. :)
