### ISSUE TITLE
LocationOverlay기능은 현재 사용이 불가능할까요?

### ISSUE THREAD

**Issue by JeongJinyong** [fornewid/naver-map-compose#53]
현재 이슈로 등록되어있는건 확인했습니다.
그래서 NaverMap에서 MapView를 직접 받아와서 접근해보려 했지만
https://fornewid.github.io/naver-map-compose/api/index.html 해당 문서에는 Compose에서 MapView를 받아오는 방법이 없는 것 같습니다.
혹시 방법이 있을까요??

**Comment by fornewid** [comment]
@JeongJinyong 
아니요. 아직은 LocationOverlay가 구현되지 않았습니다.
Compose로 사용하려고 하는데, View 구현체인 MapView를 노출하는 것은 좋은 방법이 아니라고 생각합니다.

구체적으로 어떤 기능을 사용하려고 하는지 알 수 있을까요?

**Comment by JeongJinyong** [comment]
> @JeongJinyong 아니요. 아직은 LocationOverlay가 구현되지 않았습니다. Compose로 사용하려고 하는데, View 구현체인 MapView를 노출하는 것은 좋은 방법이 아니라고 생각합니다.
> 
> 구체적으로 어떤 기능을 사용하려고 하는지 알 수 있을까요?

제가 구현하고자 하는기능은
- 자신위치를 나타내는 마커 icon 변경
- 자신위치 기준으로 Circle 추가
- 자신위치 마커에 클릭이벤트 추가
이정도 입니다.
그렇다면 locationoverlay가 아니라 매번 자신위치를 갱신할 필요는 없어서 
필요시마다 일반 마커로 만들어야할까요??

**Comment by fornewid** [comment]
@JeongJinyong
네이버지도에서 제공하는 내 위치를 변경하려는 거라면 LocationOverlay를 사용하는 것이 좋을 것 같은데요.
언제 구현할지 예정이 없어서요.
혹시 여유가 되면 직접 작업해 볼 생각도 있으신가요?

**Comment by JeongJinyong** [comment]
> @JeongJinyong 네이버지도에서 제공하는 내 위치를 변경하려는 거라면 LocationOverlay를 사용하는 것이 좋을 것 같은데요. 언제 구현할지 예정이 없어서요. 혹시 여유가 되면 직접 작업해 볼 생각도 있으신가요?

사실 직접 작업할 좋은 기회라고 생각해서 살펴보았지만 아직 제 Compose의 이해도와 익숙함으로는 너무 큰 숙제라고 생각되었습니다 ㅠㅠㅠㅠㅠ 이제 막 Compose를 사이드프로젝트에 적용하고 있는 상황이라서 이해도가 많이 부족하더라구요 ㅠ
일단 좀 더 고민해보겠습니다! 답변 감사합니다 👍

**Comment by fornewid** [comment]
@JeongJinyong 넵 ㅎㅎ

**Comment by fornewid** [comment]
[`1.3.2`](https://github.com/fornewid/naver-map-compose/releases/tag/v1.3.2) 버전에 포함되었습니다
