### ISSUE TITLE
LocationTrackingMode.Face...

### ISSUE THREAD

**Issue by isyuun-carepet** [fornewid/naver-map-compose#66]
컴포즈 전반적인 문제가 아닌가 좀 걱정인데요...
LocationTrackingMode.Face 모드시 핸드폰 방향과 일치 하지 않는것 같습니다...컴포즈로 작성된 네이버맵의 공통적인 문제인지...
네이버맵 SDK 와 비교하면 확실히 전혀 업데이트가 안됩니다...아래 화면 보시면 화면이 회전이 되지 않습니다.

![컴포즈데모앱](https://github.com/fornewid/naver-map-compose/assets/139829174/5baa476d-e4a4-4ce3-93da-5e3592ec3af2)
![네이버데모앱](https://github.com/fornewid/naver-map-compose/assets/139829174/05a4b3ca-f9a3-42fd-95f5-a76038cdd3fc)

**Comment by fornewid** [comment]
naver-map-compose 1.5.1 버전에 구현하여 반영되었습니다.
https://github.com/fornewid/naver-map-compose/releases/tag/v1.5.1

---
사용방법은
locationTrackingMode에 따라 `rememberFusedLocationSource()`의 `isCompassEnabled` 값을 `true`로 설정해주시면 됩니다.

```diff
+   val isCompassEnabled = when (locationTrackingMode) {
+       LocationTrackingMode.Follow,
+       LocationTrackingMode.Face -> true
+       else -> false
+   }
    NaverMap(
-       locationSource = rememberFusedLocationSource(),
+       locationSource = rememberFusedLocationSource(isCompassEnabled = isCompassEnabled),
        properties = MapProperties(locationTrackingMode = locationTrackingMode),
        uiSettings = MapUiSettings(
            isLocationButtonEnabled = true,
        )
    )
```
