### ISSUE TITLE
지도가 로딩되지 않는 문제

### ISSUE THREAD

**Issue by CodingHarang** [fornewid/naver-map-compose#74]
NaverMap을 호출했을 때 지도가 로딩되지 않고 아무 콘텐츠도 보이지 않는 현상이 발생합니다.
오래 기다리거나 터치를 해도 로딩이 되지 않습니다.
코드는 아래와 같습니다.
```
@OptIn(ExperimentalNaverMapApi::class)
@Composable
fun UserMapScreen(
    moveToDetailScheduleScreen: () -> Unit,
    viewModel: DetailScheduleViewModel = hiltViewModel()
) {
    BackHandler {
        moveToDetailScheduleScreen()
    }
//    Text(text = "")
    NaverMap(
        modifier = Modifier
            .fillMaxSize(),
    ) {
    }
}
```
위 코드에서 주석 처리 되어있는 Text Composable의 주석을 해제하면 제대로 로딩이 되는 것을 확인했습니다.
다른 실험을 해보았을 때 Text 대신 Box(modifier = Modifier) {} , 빈 Row, 빈 Column는 아무 효과가 없습니다.

로딩이 되지 않는 상태에서 홈 화면으로 나갔다가 들어오거나 상단바를 내렸다가 올리면 지도가 로딩되는 현상을 확인했습니다. 영상 첨부합니다.

https://github.com/fornewid/naver-map-compose/assets/95116599/7e7ff1dd-7eee-4e31-ba18-1cf18ff21c19

**Comment by fornewid** [comment]
샘플앱에서 테스트했을 때는 재현이 되지 않습니다.
UserMapScreen를 호출하는 코드도 공유할 수 있을까요?

특정 환경에서만 발생하는 것일 수도 있으니,
OS, compose 버전과 같은 정보들도 공유 부탁드립니다.

**Comment by CodingHarang** [comment]
앗 제가 정리해서 다시 메일 드리겠습니다!
