### ISSUE TITLE
OverlayImage 에 리모트에 있는 이미지를 넣을수 있는 방법 문의 드립니다

### ISSUE THREAD

**Issue by dalasjoe-1** [fornewid/naver-map-compose#84]
compose 의 Image 나 Coil 의 AsyncImage 를  바로 사용할수 있는 방법이 있을지 문의드립니다.

감사합니다

**Comment by fornewid** [comment]
naver-map-compose 라이브러리는 네이버지도 SDK를 compose에서 사용하기 용이하게 wrapping한 라이브러리입니다.
그래서 네이버지도 SDK에서 제공하지 않는 기능을 추가로 제공할 수는 없어요.

네이버지도 SDK에서 제공하는 API 중에 `OverlayImage.fromBitmap()`이 있습니다.
직접 Bitmap을 받아서 해당 API를 사용하는 것은 가능하지 않을까 싶구요.

이렇게 사용하는 것도 괜찮을지,
제약사항에 대해서는 네이버지도 SDK에 문의를 해보셔야 할 것 같습니다.
