### ISSUE TITLE
터치한 지점으로 Marker 이동

### ISSUE THREAD

**Issue by dalasjoe-1** [fornewid/naver-map-compose#85]
터치할 떄마다 해당 위치로  Marker 를 이동하려는데 잘 안됩니다.

marker.setPosition 같은 기능을 수행하려면 어떻게 해야 할까요?

아래처럼 position 에 매번 새로운 LatLng 객체를 넣어주고 있습니다.

Marker(
      state = rememberMarkerState(
          key = latLng.toString(),
          position = LatLng(mapClickedLatLng.value!!.latitude, mapClickedLatLng.value!!.longitude)
      ),

**Comment by fornewid** [comment]
답변이 많이 늦어서 죄송합니다.
아래처럼 MarkerState의 position을 변경하는 형태로 사용하시면 됩니다.

```kt
val state = rememberMarkerState()
NaverMap(
    onMapClick = { _, coord ->
        state.position = LatLng(coord.latitude, coord.longitude)
    }
) {
    Marker(state = state)
}
```
