### ISSUE TITLE
maven 저장소 추가 관련 질문 

### ISSUE THREAD

**Issue by easyhooon** [fornewid/naver-map-compose#98]
[네이버 맵 공식 문서](https://navermaps.github.io/android-map-sdk/guide-ko/1.html)의 언급된 저장소 이름과 

1) https://navermaps.github.io/android-map-sdk/guide-ko/1.html

readme 에 적힌 저장소의 이름이 다른데 

2) https://naver.jfrog.io/artifactory/maven/

readme 에 적힌 maven 저장소만 추가해도 가능한 게 맞을까요? 아니면 둘다 추가해야하는 것인지 궁금합니다. 

현재 1번만 추가하여서 작업 중이었는데, 이를 제거하고 2번을 추가하고 앱을 빌드 할 경우,
 `Could not find com.naver.maps:map-sdk:3.18.0.Searched in the following locations:` 에러가 발생하여, 문서 이해에 혼동이 있어 질문 드립니다.
1번과 2번을 모두 추가할 경우엔 정상적으로 빌드됩니다.

관련한 에러 캡쳐본입니다.
<img width="1337" alt="image" src="https://github.com/fornewid/naver-map-compose/assets/51016231/7caf6d51-2541-4f68-a842-35434d7a8f70">

**Comment by fornewid** [comment]
아래 maven 주소는 모두 네이버지도 SDK 저장소 주소입니다.
- 3.18.0 미만: https://naver.jfrog.io/artifactory/maven/
- 3.18.0 이상: https://repository.map.naver.com/archive/maven

현재 [naver-map-compose](https://github.com/fornewid/naver-map-compose) 라이브러리는 네이버지도 3.16.0 SDK 기반으로 배포되어 있어서, 2개의 저장소 주소가 모두 필요합니다.

네이버지도 SDK 저장소 주소가 최근 변경되는 바람에...;;
이건 라이브러리를 추가로 배포해야 할 것 같은데요.

어느 버전의 [naver-map-compose](https://github.com/fornewid/naver-map-compose) 라이브러리를 사용하시는지 궁금합니다.

**Comment by easyhooon** [comment]
<img width="401" alt="image" src="https://github.com/fornewid/naver-map-compose/assets/51016231/0e623a3b-b639-47da-8d56-05b67ced5536">

현재 사용하는 버전들은 다음과 같습니다. 1.6.0 버전으로 올리면 다른 컴포즈 컴포넌트들과 충돌이 발생하여 1.5.5버전으로 downgrade? 하여 사용중입니다.
1.6.0 버전으로 올려서 빌드하면 이런 의미를 알기 어려운 에러가 발생하네요
`java.lang.NoSuchMethodError: No static method HorizontalPager-xYaah8o(Landroidx/compose/foundation/pager/PagerState;Landroidx/compose/ui/Modifier;Landroidx/compose/foundation/layout/PaddingValues;Landroidx/compose/foundation/pager/PageSize;IFLandroidx/compose/ui/Alignment$Vertical;Landroidx/compose/foundation/gestures/snapping/SnapFlingBehavior;ZZLkotlin/jvm/functions/Function1;Landroidx/compose/ui/input/nestedscroll/NestedScrollConnection;Lkotlin/jvm/functions/Function4;Landroidx/compose/runtime/Composer;III)V in class Landroidx/compose/foundation/pager/PagerKt; or its super classes (declaration of 'androidx.compose.foundation.pager.PagerKt' appears in /data/app/~~G-v7p06KVhI4omuhZL8C4w==/com.unifest.android.dev-Jq7KHLLy1IK8qX5jvqcKxA==/base.apk)`

**Comment by fornewid** [comment]
네, 내부적으로 [naver-map-compose](https://github.com/fornewid/naver-map-compose) 라이브러리가 네이버지도 SDK에 의존성을 갖고 있어서
따로 선언하지 않아도 사용할 수 있습니다.

다만 네이버지도 SDK 버전만 업데이트하고 싶은 경우에는 추가하시면 되구요.

**Comment by fornewid** [comment]
Compose 1.6은 [naver-map-compose](https://github.com/fornewid/naver-map-compose) 라이브러리 1.5.X 와 일치합니다.
버전 체계가 서로 달라서요. ㅎㅎ

![](https://github.com/fornewid/naver-map-compose/assets/3405740/4e9e5a81-6f50-4531-a887-9154646713da)

**Comment by fornewid** [comment]
README.md에도 반영되었습니다.
