### ISSUE TITLE
위치 오버레이 관련 질문

### ISSUE THREAD

**Issue by easyhooon** [fornewid/naver-map-compose#99]
https://github.com/fornewid/naver-map-compose/issues/53
해당 이슈를 읽어보았으나, 

혹시 현 시점에서 다음과 같은 사용자 위치 오버레이는 naver-map-compose에서 구현이 불가능한 것인가요?
<img width="240" src="https://github.com/fornewid/naver-map-compose/assets/51016231/5b59b5b6-e72f-4b95-91f5-1f27df0a0dec">
(android view system 의 naver-map 을 사용한 앱 입니다.) 

LocationTrackingMode 를 None 이 아닌 값으로 설정해보아도 사용자의 위치를 표시하는 오버레이가 보이지 않아 질문드립니다.

**Comment by easyhooon** [comment]
Demo 앱 내에 LocationTrackingScreen 예제를 확인하여 가능함을 확인하였습니다!

더욱이, rememberFusedLocationSource 를 통해 직접 권한 요청 관련한 작업을 해주지 않아도 되는 것을 확인하였습니다.
관련한 작업에서 fusedLocation 객체를 Activity에 둬야할지, Composable Screen 내에 둬야할지, Viewmodel 에 둬야할지, 상당히 애를 먹었는데, 수고를 덜어주셔서 감사드립니다!

**Comment by fornewid** [comment]
넵, 네이버지도 SDK에서는 Activity/Fragment가 있어야 FusedLocationSource을 사용할 수 있는 제약이 있습니다.
그래서 Context만 있으면 사용할 수 있게 `rememberFusedLocationSource()`를 재구현했습니다.

Composable Screen에 두어도 괜찮도록 의도하여 만들었지만,
혹시라도 사용하다가 이슈가 있으시면 공유 부탁드리겠습니다. 🙇 

데모 코드를 확인해보신 것 같아서, 사용방법은 더 말씀드리지 않을게요. :)
